project:
  type: website
  output-dir: docs
  
website:
  title: "Irene Zhang's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: research.qmd
        text: Research
      - href: resume.qmd
        text: Resume
    tools:
      - icon: instagram
        href: https://instagram.com/irenez0516
      - icon: github
        href: https://github.com/irenez0516
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Irene Zhang"

format:
  html:
    theme: flatly
    toc: true

editor: source

